[package]
name = "gnostr-bitcoin"
version = "1910.922229.829806"
edition = "2024"
repository = "https://github.com/gnostr-org/gnostr-bitcoin.git"
description = "gnostr: a git+nostr workflow utility."
homepage = "https://github.com/gnostr-org/gnostr-bitcoin"
authors = ["gnostr admin@gnostr.org"]

[package.metadata.wix]
upgrade-guid = "ACDBED36-EF11-48AF-9C23-1CD76EC60D69"
path-guid = "F8A0CC6D-BA1A-4B65-BF01-86C1FD861252"
license = false
eula = false

[lib]
name = "gnostr_bitcoin"
path = "src/lib.rs"

[[bin]]
name = "gnostr-bitcoin"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.86"
crossterm = "0.27.0"
ctrlc = { version = "3.4.4", features = ["termination"] }
dirs = "5.0.0"
log = "0.4.21"
rand = "0.9.2"
ratatui = "0.26.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
simplelog = "0.12.2"
time = { version = "0.3", features = ["macros", "formatting"] }
clap = { version = "4.5.20", features = ["derive", "env", "cargo"] }
#anyhow = "1.0.98"
bitcoin = { version = "0.32.5", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"
#clap = { version = "4.5.38", features = ["derive"] }
hex = "0.4"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
#rand = "0.9.1"
arti-client = { version = "0.30", features = ["onion-service-client"] }
tor-rtcompat = { version = "0.30", features = ["tokio"] }
data-encoding = "2.9.0"
sha3 = "0.10.8"


# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
